<?php

function taxcess_fix_permission() {
  $permissions = array();

  foreach ( taxonomy_get_vocabularies() AS $vid => $vocabulary ) {
    $permissions['add terms in ' . $vid] = array(
      'title' => t('Add terms in %vocabulary', array('%vocabulary' => $vocabulary->name)),
    );
  }

  return $permissions;
}

function taxcess_fix_menu_alter(&$items) {
  // vocabularies list
  $item = &$items['admin/structure/taxonomy'];
  $item['access callback'] = 'taxcess_fix_access';
  $item['access arguments'] = array('index');

  // terms list in vocabulary
  $item = &$items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name'];
  $item['access callback'] = 'taxcess_fix_access';
  $item['access arguments'] = array('list terms', 3);

  // add term to vocabulary
  $item = &$items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/add'];
  $item['access callback'] = 'taxcess_fix_access';
  $item['access arguments'] = array('add terms', 3);
}

function taxcess_fix_access($op, $vocabulary = null) {
  // admin: always
  if ( user_access('administer taxonomy') ) {
    return TRUE;
  }

  // others: well, that depends
  switch ( $op ) {
    case 'index':
      // only if they have >= 1 vocabulary access
      foreach ( taxonomy_get_vocabularies() AS $vid => $vocabulary ) {
        if ( user_access('edit terms in ' . $vid) || user_access('delete terms in ' . $vid) ) {
          return TRUE;
        }
      }
      break;
    case 'list terms':
      if ( $vocabulary ) {
        $vid = $vocabulary->vid;
        if ( user_access('edit terms in ' . $vid) || user_access('delete terms in ' . $vid) ) {
          return TRUE;
        }
      }
      break;
    case 'add terms':
      if ( $vocabulary ) {
        $vid = $vocabulary->vid;
        if ( user_access('add terms in ' . $vid) ) {
          return TRUE;
        }
      }
      break;
  }
}
